"""
Initial migration for cards app.

Creates the following models:
- Lesson (with title and creation timestamp)
- Card (with word, translation, image and lesson relationship)
"""
# pylint: disable=invalid-name
# Generated by Django 4.2.20 on 2025-04-13 11:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Initial database migration for cards application.

    Creates the necessary database tables for Lesson and Card models
    with all required fields and validators.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('title', models.CharField(
                    max_length=100,
                    validators=[
                        django.core.validators.MinLengthValidator(
                            3,
                            'Название должно быть не короче 3 символов!'
                        )
                    ]
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('word', models.CharField(
                    max_length=50,
                    validators=[
                        django.core.validators.MinLengthValidator(
                            2,
                            'Слово должно быть не короче 2 символов!'
                        )
                    ]
                )),
                ('translation', models.CharField(
                    max_length=50,
                    validators=[
                        django.core.validators.MinLengthValidator(
                            2,
                            'Перевод должен быть не короче 2 символов!'
                        )
                    ]
                )),
                ('image', models.ImageField(
                    blank=True,
                    null=True,
                    upload_to='cards/'
                )),
                ('lesson', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='cards',
                    to='cards.lesson'
                )),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
